Rule generator
webhintio/hint pull request #264
Opened 2017-06-13 22:47 UTC by qzhou1607-zz

Fix issue #238

Also added a simple rule remover.

2017-06-13 23:24 UTC, molant requested changes
Can you add also tests for this? @sarvaje can tell you where things should go.

2017-06-15 22:27 UTC, molant requested changes

2017-06-15 22:30 UTC, sarvaje requested changes

2017-06-16 20:53 UTC, molant requested changes
@qzhou1607 some last minute changes. Can you please take care of them asap?

2017-06-16 21:01 UTC, molant requested changes

2017-06-19 18:25 UTC, sarvaje requested changes

2017-06-19 21:46 UTC, sarvaje approved these changes

2017-06-19 21:47 UTC, merged